export const ADD_USER_DATA = "ADD_USER_DATA";
export const LOGIN = "LOGIN";
export const LOGOUT = "LOGOUT";
export const ADD_USER_CONVERSION = "ADD_USER_CONVERSION";
export const DELETE_CONVERSION = "DELETE_CONVERSION";
export const ADD_LOGIN_BUTTON_STATUS = "ADD_LOGIN_BUTTON_STATUS";
export const CHANGE_USER_EMAIL = "CHANGE_USER_EMAIL";
